<?php

    return [
        'main/view' => 'Public/Main/view',
        'main/create' => 'Public/Main/create',
        'main/update' => 'Public/Main/update',
        'main/delete' => 'Public/Main/delete',
        'about/view' => 'Public/About/view',
        'about/create' => 'Public/About/create',
        'about/update' => 'Public/About/update',
        'about/delete' => 'Public/About/delete',
        'gallery/view' => 'Public/Gallery/view',
        'gallery/create' => 'Public/Gallery/create',
        'gallery/update' => 'Public/Gallery/update',
        'gallery/delete' => 'Public/Gallery/delete',
        'error404/index' => 'Public/Error404/index',

        'admin/main/view' => 'Admin/Main/view',
        'admin/main/create' => 'Admin/Main/create',
        'admin/main/update' => 'Admin/Main/update',
        'admin/main/delete' => 'Admin/Main/delete',
        'admin/about/view' => 'Admin/About/view',
        'admin/about/create' => 'Admin/About/create',
        'admin/about/update' => 'Admin/About/update',
        'admin/about/delete' => 'Admin/About/delete',
        'admin/gallery/view' => 'Admin/Gallery/view',
        'admin/gallery/create' => 'Admin/Gallery/create',
        'admin/gallery/update' => 'Admin/Gallery/update',
        'admin/gallery/delete' => 'Admin/Gallery/delete',
        'admin/error404/index' => 'Admin/Error404/index',
    ];
